### ISSUE TITLE
Rain gauge no hour, day or week rapport

### ISSUE THREAD

**Issue by tonbor** [matthias-bs/BresserWeatherSensorReceiver#129]
**Context**
- Which example sketch are you using? [BresserWeatherSensorMQTT.ino](https://github.com/matthias-bs/BresserWeatherSensorReceiver/blob/main/examples/BresserWeatherSensorMQTT/BresserWeatherSensorMQTT.ino)
- Which changes to the code did you make (if any)? NONE
- Which sensor are you using?
7-in-1 868 MHz Weather Sensor Radio Receiver 7003240
**Describe the bug**
{"id":43961,"ch":0,"battery_ok":1,"temp_c":10.5,"humidity":69,"wind_gust":0.6,"wind_avg":0.6,"wind_dir":168.0,"uv":1.0,"light_klx":11.6,"rain":18.2,"rain_h":0.0,"rain_d":0.0,"rain_w":0.0,"rain_m":18.2}
To day 3.3 rain, is on the default screen so rain_h":0.0,"rain_d":0.0,"rain_w":0.0, is error
**To Reproduce**
1. Step1 '...'
2. Step2 '....'
3. Step3 '....'
4. See error rain":18.2,"rain_h":0.0,"rain_d":0.0,"rain_w":0.0,"rain_m":18.2}

**Expected behavior**
A clear and concise description of what you expected to happen. rain":18.2,"rain_h":0.0,"rain_d":3.3,"rain_w":3.3,"rain_m":18.2}

**Debug Log**
If applicable, add log file to help explain your problem.
 - Build log file (enable verbose output in the Arduino IDE: File->Preferences - "Show verbose output during: compile")
 - Serial console log file (see [Debug Output Configuration in Arduino IDE](https://github.com/matthias-bs/BresserWeatherSensorReceiver/blob/main/DEBUG_OUTPUT.md))

**Embedded Device (please complete the following information):**
 - Arduino IDE Version: [e.g. 2.2]
 - ESP32/ESP8266 Board Support Package Version: [e.g. ESP32 2.0.7]
 - Library Version [e.g. 0.6.1]
 - Your Board: [brand/model/version] (if unsure, attach a photo)[Heltec WiFi LoRa32 V2](https://heltec.org/project/wifi-lora-32/)
 - Selected Board in the Arduino IDE: [brand/model/version] Heltec WiFi LoRa 32(V2) version 1.1.5
 - Your Radio Transceiver Module (if external): [brand/model/chipset/frequency] 
 - **Pinning/Wiring**

**Additional context**

**Comment by tonbor** [comment]
I suppose when recompiling the history get lost. That is the reason I think.

**Comment by matthias-bs** [comment]
In general, the calculated values might differ from the values the display shows, because we do not know how the station actually calculates these values.

This project resets the daily rain counter at 0:00h. Likewise, the weekly counter is reset each Monday at 0:00h and the monthly counter at the first day of each month at 0:00h. As a prerequisite, the correct time and date have to be available (set via NTP) and the correct timezone has to be configured (in the config header file). 

It depends on the IDE configuration if the history is lost when recompiling or not:
![grafik](https://github.com/matthias-bs/BresserWeatherSensorReceiver/assets/83612361/35d901f2-7a0b-4888-89c9-ee39cbb1eb9e)

Currently, the history might also have got lost due to changes in the implementation.

If you think this issue still persists, please provide more information:
* Build log file
* Serial console log file
* Library Version

**Comment by tonbor** [comment]
{
  "id": 43961,
  "ch": 0,
  "battery_ok": 1,
  "temp_c": 7.6,
  "humidity": 89,
  "wind_gust": 3.1,
  "wind_avg": 2.7,
  "wind_dir": 160,
  "uv": 0,
  "light_klx": 0.2,
  "rain": 22.3,
  "rain_h": 0.7,
  "rain_d": 0.8,
  "rain_w": 4.1,
  "rain_m": 22.3
}
Think it is ok, thanjs for the good work matthias
