### ISSUE TITLE
Support for 7003100?

### ISSUE THREAD

**Issue by okainov** [matthias-bs/BresserWeatherSensorReceiver#71]
Does this script support https://www.bresser.de/Wetter-Zeit/Wettercenter/BRESSER-7-in-1-Exklusive-ClimateScout-Funk-Wetterstation-schwarz.html?mtm_campaign=Doofinder&mtm_kwd=7003100CM3000&mtm_source=German&mtm_medium=OnSite&mtm_cid=Germany&mtm_group=SiteSearch ? It's not listed in the supported models...

**Comment by matthias-bs** [comment]
I cannot make any promises, but I am pretty confident that it will work. Some sensors which are known to work are listed on the web page under "accessories", especially the 7803300 (external 7-in-1 sensor spare part).

If you try, please let me know the result.

**Comment by marxu** [comment]
Hello.
My English is very bad.
I have bought this 433M v2.0 and I have this station 7003100CM3000
I leave you the link, I hope it turns out well.
If someone could help me get it working, that would be nice.
Anyway, I'll go practicing. I'll inform you.
Thank you.
[]()https://es.aliexpress.com/item/1005002074380868.html?spm=a2g0o.order_list.order_list_main.5.3c1b194dBgPzCH&gatewayAdapt=glo2esp

**Comment by matthias-bs** [comment]
Hi,
I'm afraid this will not work. You have bought a transceiver module for 433 MHz, but the weather sensor transmits at 868 MHz.

**Comment by marxu** [comment]
Hi, this is what I'm doing, my idea is to do it with an arduino nano and via USB to the raspberry.
I have used the library:
#include <ELECHOUSE_CC1101_SRC_DRV.h>
ELECHOUSE_cc1101.Init();              // must be set to initialize the cc1101!
    ELECHOUSE_cc1101.setCCMode(1);       // set config for internal transmission mode.
    ELECHOUSE_cc1101.setModulation(0);  // set modulation mode. 0 = 2-FSK, 1 = GFSK, 2 = ASK/OOK, 3 = 4-FSK, 4 = MSK.
    //ELECHOUSE_cc1101.setMHZ(433.92);   // Here you can set your basic frequency. The lib calculates the frequency automatically (default = 433.92).The cc1101 can: 300-348 MHZ, 387-464MHZ and 779-928MHZ. Read More info from datasheet.
    ELECHOUSE_cc1101.setMHZ(868);<-----------
    ELECHOUSE_cc1101.setSyncMode(2);  // Combined sync-word qualifier mode. 0 = No preamble/sync. 1 = 16 sync word bits detected. 2 = 16/16 sync word bits detected. 3 = 30/32 sync word bits detected. 4 = No preamble/sync, carrier-sense above threshold. 5 = 15/16 + carrier-sense above threshold. 6 = 16/16 + carrier-sense above threshold. 7 = 30/32 + carrier-sense above threshold.
    ELECHOUSE_cc1101.setCrc(1);      // 1 = CRC calculation in TX and CRC check
I managed to get this, but I don't know what it is.
---->120,133,219,69,234,48,247,79,24,244,9,243,141,127,152,35,82,98,186,0,207,6,159,47,56,43,10,55,142,63,137,48,115,

**Comment by matthias-bs** [comment]
I don't know this ELECHOUSE driver and I do not understand how this is related to this project.

The CC1101 may support the frequencies mentioned in the comment above, but which frequency can actually be used is restricted by some components (especially the crystal oscillator) on the printed circuit board.

**Comment by marxu** [comment]
Hi Matthias-bs, as you will see I am very green with all this. Could you give me a valid link so I can buy it? I have that same weather station. Thank you.

**Comment by matthias-bs** [comment]
Hi,

please have a look at this: https://github.com/matthias-bs/BresserWeatherSensorReceiver#cc1101

Apparently, there are still no 868 MHz versions with a proper antenna connector and a decent pin header.

I hesitate to provide a link, because I made the experience that a significant number of modules delivered do not work. This is not the fault of TI (the chip manufacturer), but caused by bad manufacturing or handling of the parts and modules.

If you send me a link (or a few alternatives), I can confirm if the choice is correct based on the specifications provided.

Sorry to make it more complicated than usually needed, but I do not want to be responsible if you get defective parts.

**Comment by matthias-bs** [comment]
The easiest way to get started is one of the supported boards listed in [Configuration by selecting a supported Board in the Arduino IDE](https://github.com/matthias-bs/BresserWeatherSensorReceiver#configuration-by-selecting-a-supported-board-in-the-arduino-ide). From this table, select a board which does not need additional wiring (see column "notes"). 

Make sure to get the 868 MHz version!

Then upload any of the examples (I highly recommend to start with [BresserWeatherSensorBasic](https://github.com/matthias-bs/BresserWeatherSensorReceiver/tree/main/examples/BresserWeatherSensorBasic) and proceed from there.

**Comment by matthias-bs** [comment]
Closed due to inactivity.

**Comment by Calimerorulez** [comment]
I've ordered one too, and am happy to experiment if it helps.
